services:
  # Le service pour la base de données
  mongodb:
    image: mongo:7.0
    container_name: mongodb_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Le service pour ton code NestJS
  api:
    build: .
    container_name: nestjs_api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/blog_db
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data: