services:
  # Le service pour la base de données
  mongodb:
    image: mongo:7.0
    container_name: mongodb_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Le service pour ton code NestJS
  api:
    build: .
    container_name: nestjs_api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/blog_db
    depends_on:
      mongodb:
        condition: service_healthy
  
  rustfs_perms:
    image: alpine
    user: root
    volumes:
      - /mnt/rustfs/data:/fix_path
    command: chown -R 10001:10001 /fix_path

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs-server
    depends_on:
      rustfs_perms:
        condition: service_completed_successfully
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLE=true
    volumes:
      - /mnt/rustfs/data:/data
    command: ["--address", ":9000", "--console-enable", "/data"]
    restart: unless-stopped

volumes:
  mongo_data: